#SPDX-License-Identifier: MIT-0
---
# tasks file for simple-ansible-docker


- name: Install required packages
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  